index:
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::index' }

hapiness:
    path: /happiness
    defaults: { _controller: 'App\Controller\DefaultController::happiness' }

# first, run composer req annotations
#controllers:
#    resource: ../src/Controller/
#    type: annotation
